# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
