# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gid', models.UUIDField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(0, b'Draft'), (1, b'In Progress'), (2, b'Published')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gid', models.UUIDField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=b'/images')),
                ('audio', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=b'/audio')),
                ('position', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(choices=[(0, b'Draft'), (1, b'In Progress'), (2, b'Pending Approval'), (3, b'Published')], default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.Course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set([('course', 'position')]),
        ),
    ]
