# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='gid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
