# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160904_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
