# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_slide_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
