# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 13:41
from __future__ import unicode_literals


from django.db import migrations, models

from scholars.courses.models import get_audio_path, get_image_path


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160911_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='slide',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=get_audio_path),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=get_image_path),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set([]),
        ),
    ]
