# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-26 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20160911_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.PositiveIntegerField(choices=[(0, b'Unknown'), (1, b'Audio'), (2, b'Graphics'), (3, b'Scripting'), (4, b'DRI'), (5, b'Super DRI')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='doi',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.PositiveIntegerField(choices=[(0, b'Teaming'), (1, b'Planning'), (2, b'Scripting'), (3, b'Audio')], default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='pages',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='publisher',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, b'Proposed'), (1, b'In Progress'), (2, b'Published')], default=0),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
