# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mode',
        ),
        migrations.AddField(
            model_name='course',
            name='phase',
            field=models.PositiveIntegerField(choices=[(0, b'Onboarding'), (1, b'Reading'), (2, b'Discussion'), (3, b'Slides'), (4, b'Scripting'), (5, b'Audio'), (6, b'Peer Review'), (7, b'Pending Approval')], default=0),
        ),
    ]
