# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170629_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemember',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, b'Unknown'), (1, b'Presentation'), (2, b'Graphics'), (3, b'Scripting'), (4, b'Audio'), (5, b'DRI'), (6, b'Super DRI')], default=0),
        ),
    ]
