# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170718_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='phase',
            field=models.PositiveIntegerField(choices=[(0, b'Onboarding'), (1, b'Reading'), (2, b'Discussion'), (3, b'Slides'), (4, b'Peer Review'), (5, b'Audio'), (6, b'Refinement'), (7, b'Pending Approval')], default=0),
        ),
    ]
