# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170718_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together=set([('course', 'member', 'role')]),
        ),
    ]
