# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170810_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='shortcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
