# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170810_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='dri',
            field=models.BooleanField(default=False),
        ),
    ]
