# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 11:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20170812_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_audio_actual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='num_dri_actual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='num_graphics_actual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='num_presentation_actual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='num_scripting_actual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_graphics',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
