# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20170822_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=2048),
        ),
    ]
